#!/bin/bash
# Push KRISPER to GitHub

echo "🧬 Pushing KRISPER to GitHub..."
echo ""
echo "The repository is ready to push!"
echo ""
echo "Run these commands:"
echo ""
echo "1. If you haven't created the repo on GitHub yet:"
echo "   Go to https://github.com/new"
echo "   Create repository named: krisper"
echo "   Make it public"
echo "   Don't initialize with README"
echo ""
echo "2. Then push with:"
echo "   git push -u origin main"
echo ""
echo "3. If it asks for credentials:"
echo "   Username: echo313unfolding"
echo "   Password: (use a Personal Access Token, not your password)"
echo ""
echo "To create a Personal Access Token:"
echo "- Go to GitHub Settings → Developer Settings → Personal Access Tokens"
echo "- Generate new token with 'repo' permissions"
echo ""
echo "Or use SSH if you have it set up:"
echo "git remote set-url origin git@github.com:echo313unfolding/krisper.git"
echo "git push -u origin main"